### ISSUE TITLE
Add privacy policy as extra page

### ISSUE THREAD

**Issue by digitarald** [mozilla/firehug#61]
Provide final text for privacy policy.

**Comment by digitarald** [comment]
Can you add the text here, @dailycavalier?

**Comment by dailycavalier** [comment]
Here is the privacy policy text that our privacy friends provided:

The Summit app is designed to enhance your Summit experience. The four features are: a schedule of events, information for getting around, a Healthy Dialog breakfast activity that assigns Mozillians to groups each day, and a 3 Questions response form to measure the pulse of the collective Summit experience. 

We care about your privacy and you should know the following:
- If you choose to respond to the optional 3 Questions response form, your responses will be collected by Mozilla and used as described in this notice. 
- Your list of positive impact people and Healthy Dialog groupings will be stored with your mozillians.org username so that it can be made available to you after the Summit. 
- Mozilla will use your responses to analyze and share aggregate connections amongst Mozillians. You can request deletion of this data at any time by contacting summit2013-app@mozilla.com.  
- This app is integrated with Persona and mozillians.org, our community directory. 
  Their privacy policies apply and can be found at:
  http://www.mozilla.org/persona/privacy-policy/
  http://mozilla.org/privacy-policy.html

**Comment by operatorjen** [comment]
https://github.com/digitarald/firehug/commit/3b538d8975228e70eecb17a953c9c5f89aeb806c
