### ISSUE TITLE
Can't submit a 2nd "3 Questions"

### ISSUE THREAD

**Issue by pfinette** [mozilla/firehug#70]
After submitting my "3 Questions" and when I use the in-app back button - everytime I try to submit another "3 Questions" I get the "Thank You" page. When I reload the app I get a "Submission Failed. Try Again" error message.

iOS 7, Chrome.

**Comment by pfinette** [comment]
Confirmed behavior for Safari/iOS as well.

**Comment by dailycavalier** [comment]
The behavior is by design, but we can use a better error message. We chose to restrict the form so it can only be submitted every two hours, so folks don't get submission-happy. @digitarald - perhaps we can include an error message like this when someone tries to submit more than once in a short time period?

"Thanks, we got your previous submission. You can answer the 3 Questions again in two hours. Now go have fun at the Summit!"

**Comment by digitarald** [comment]
ok, this needs better messaging. It will eventually enable itself after 2 hours. We could show a countdown or simply a "please wait" message.

**Comment by dailycavalier** [comment]
Some suggested text for a "please wait" message: "Please wait. You can answer the 3 Questions again after two hours have elapsed. Now go have fun at the Summit!"
