### ISSUE TITLE
Summit app schedule

### ISSUE THREAD

**Issue by mardid** [mozilla/firehug#76]
I would expect to see Keynotes as well as sessions and I would remove hours for Lounge + Hack space in the linear render (save for grid only.)

**Comment by digitarald** [comment]
The schedule can be tweaked in the Spreadsheet, maybe cleaned up a bit.

**Comment by mardid** [comment]
I tried to access but could not. Alas. Can we open the spreadsheet to all? 

----- Original Message -----

**Comment by dailycavalier** [comment]
Mardi, you should be able to edit the schedule spreadsheet using your
mdouglass Mozilla email. I'd prefer to not make the spreadsheet editable by
everyone, since that opens the app up to some risks we'd rather not deal
with. Let me know if you still have trouble editing and we'll find a
solution.

On Tue, Oct 1, 2013 at 9:53 AM, mardid notifications@github.com wrote:

> I tried to access but could not. Alas. Can we open the spreadsheet to all?
> 
> ----- Original Message -----
> 
> From: "Harald Kirschner" notifications@github.com
> To: "digitarald/firehug" firehug@noreply.github.com
> Cc: "mardid" mdouglass@mozilla.com
> Sent: Tuesday, October 1, 2013 9:43:29 AM
> Subject: Re: [firehug] Summit app schedule (#76)
> 
> The schedule can be tweaked in the Spreadsheet, maybe cleaned up a bit.
> 
> —
> Reply to this email directly or view it on GitHub .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/digitarald/firehug/issues/76#issuecomment-25468000
> .

## 

William
